GET http://localhost:9090/users

###

POST http://localhost:9090/users
Content-Type: application/json

{
    "username": "laugh123",
    "email": "laugh@example.com",
    "password": "passwordl987",
    "habit_categories": [],
    "challenges": [],
    "habits": [],
    "notes": []
}

###